package model

type (
	// 公司
	Company struct {
		Index     int64  `gorm:"column:index;primary_key"` // 索引
		StockCode int64  `gorm:"column:stockCode;"`        // 股票代码
		Market    string `gorm:"column:market"`            // 市场类型 a
		IpoDate   string `gorm:"column:ipoDate"`           // IPO时间
		AreaCode  string `gorm:"column:areaCode"`          // 区域代码 cn
		Name      string `gorm:"column:name"`              // 公司名称
		FsType    string `gorm:"column:fsType"`            // 财报类型

		// TODO 公司个性化配置项
	}

	// 利润表
	Profit struct {
		StockCode                   int64 `gorm:"column:stockCode:primary_key"`         // 股票代码
		Toi                         int64 `gorm:"column:toi"`                           // 营业总收入
		Oi                          int64 `gorm:"column:oi"`                            // 营业收入
		Ii                          int64 `gorm:"column:ii"`                            // 利息收入
		Ep                          int64 `gorm:"column:ep"`                            // 已赚保费
		Faci                        int64 `gorm:"column:faci"`                          // 手续费及佣金收入
		Ooi                         int64 `gorm:"column:ooi"`                           // 其他业务收入
		Toc                         int64 `gorm:"column:toc"`                           // 营业总成本
		Oc                          int64 `gorm:"column:Oc"`                            // 营业成本
		GpM                         int64 `gorm:"column:gp_m"`                          // 毛利率
		Ie                          int64 `gorm:"column:ie"`                            // 利息支出
		Face                        int64 `gorm:"column:face"`                          // 手续费及佣金支出
		S                           int64 `gorm:"column:s"`                             // 退保金
		Ce                          int64 `gorm:"column:ce"`                            // 保险合同赔付支出
		Iiicr                       int64 `gorm:"column:iiicr"`                         // 提取保险责任准备金净额
		Phdrfpip                    int64 `gorm:"column:phdrfpip"`                      // 保单红利支出
		Rie                         int64 `gorm:"column:rie"`                           // 分保费用
		Tas                         int64 `gorm:"column:tas"`                           // 税金及附加
		Se                          int64 `gorm:"column:se"`                            // 销售费用
		Ae                          int64 `gorm:"column:ae"`                            // 管理费用
		Rade                        int64 `gorm:"column:rade"`                          // 研发费用
		Fe                          int64 `gorm:"column:fe"`                            // 财务费用
		Ieife                       int64 `gorm:"column:ieife"`                         // 利息费用
		Iiife                       int64 `gorm:"column:iiife"`                         // 利息收入
		SeR                         int64 `gorm:"column:se_r"`                          // 销售费用率
		AeR                         int64 `gorm:"column:ae_r"`                          // 管理费用率
		RadeR                       int64 `gorm:"column:rade_r"`                        // 研发费用率
		FeR                         int64 `gorm:"column:fe_r"`                          // 财务费用率
		OeR                         int64 `gorm:"column:oe_r"`                          // 总营业费用率
		TeR                         int64 `gorm:"column:te_r"`                          // 三项费用率
		Oic                         int64 `gorm:"column:oic"`                           // 其他收益
		Ivi                         int64 `gorm:"column:ivi"`                           // 投资收益
		Iifaajv                     int64 `gorm:"column:iifaajv"`                       // 对联营企业及合营企业的投资收益
		Iftdofamaac                 int64 `gorm:"column:iftdofamaac"`                   // 以摊余成本计量的金融资产终止确认产生的投资收益
		Ei                          int64 `gorm:"column:ei"`                            // 汇兑收益
		Nehb                        int64 `gorm:"column:nehb"`                          // 净敞口套期收益
		Ciofv                       int64 `gorm:"column:ciofv"`                         // 公允价值变动收益
		Cilor                       int64 `gorm:"column:cilor"`                         // 信用减值损失
		Ailor                       int64 `gorm:"column:ailor"`                         // 资产减值损失
		Oail                        int64 `gorm:"column:oail"`                          // 其他资产减值损失
		Adi                         int64 `gorm:"column:adi"`                           // 资产处置收益
		Op                          int64 `gorm:"column:op"`                            // 营业利润
		OpSR                        int64 `gorm:"column:op_s_r"`                        // 营业利润率
		OpOpR                       int64 `gorm:"column:op_op_r"`                       // 其他营业利润占比
		Noi                         int64 `gorm:"column:noi"`                           // 营业外收入
		Ncadarg                     int64 `gorm:"column:ncadarg"`                       // 非流动资产毁损报废利得
		Noe                         int64 `gorm:"column:noe"`                           // 营业外支出
		Ncadarl                     int64 `gorm:"column:ncadarl"`                       // 非流动资产毁损报废损失
		Tp                          int64 `gorm:"column:tp"`                            // 利润总额
		RadeTpR                     int64 `gorm:"column:rade_tp_r"`                     // 研发费占利润总额比值
		Ite                         int64 `gorm:"column:ite"`                           // 所得税费用
		IteTpR                      int64 `gorm:"column:ite_tp_r"`                      // 有效税率
		Np                          int64 `gorm:"column:np"`                            // 净利润
		NpSR                        int64 `gorm:"column:np_s_r"`                        // 净利润率
		Npfco                       int64 `gorm:"column:npfco"`                         // 持续经营净利润
		Npfdco                      int64 `gorm:"column:npfdco"`                        // 终止经营净利润
		Wroe                        int64 `gorm:"column:wroe"`                          // 归属于母公司普通股股东的加权ROE
		Npatshaoehopc               int64 `gorm:"column:npatshaoehopc"`                 // 归属于母公司股东及其他权益持有者的净利润
		Npatoshopc                  int64 `gorm:"column:npatoshopc"`                    // 归属于母公司普通股股东的净利润
		Npadnrpatoshaopc            int64 `gorm:"column:npadnrpatoshaopc"`              // 归属于母公司普通股股东的扣除非经常性损益的净利润
		NpadnrpatoshaopcNpatoshopcR int64 `gorm:"column:npadnrpatoshaopc_npatoshopc_r"` // 扣非净利润占比
		Npatoeihopc                 int64 `gorm:"column:npatoeihopc"`                   // 归属于母公司其他权益工具持有者的净利润
		Npatmsh                     int64 `gorm:"column:npatmsh"`                       // 少数股东损益
		Natooci                     int64 `gorm:"column:natooci"`                       // 其他综合收益的税后净额
		Tci                         int64 `gorm:"column:tci"`                           // 综合收益总额
		Tciatshaoehopc              int64 `gorm:"column:tciatshaoehopc"`                // 归属于母公司股东及其他权益持有者的综合收益总额
		Tciatoshopc                 int64 `gorm:"column:tciatoshopc"`                   // 归属于母公司普通股股东的综合收益总额
		Tciatmsh                    int64 `gorm:"column:tciatmsh"`                      // 归属于少数股东的综合收益总额
		Beps                        int64 `gorm:"column:beps"`                          // 基本每股收益
		Deps                        int64 `gorm:"column:deps"`                          // 稀释每股收益
	}

	// 资产负债表
	BalanceSheet struct {
		Ta           int64 `gorm:"column:ta"`             // 资产合计
		Nwc          int64 `gorm:"column:nwc"`            // 净营运资本
		Tca          int64 `gorm:"column:tca"`            // 流动资产合计
		TcaTaR       int64 `gorm:"column:tca_ta_r"`       // 流动资产占比
		Cabb         int64 `gorm:"column:cabb"`           // 货币资金
		CabbTaR      int64 `gorm:"column:cabb_ta_r"`      // 货币资金占比
		Sr           int64 `gorm:"column:sr"`             // 结算备付金
		Pwbaofi      int64 `gorm:"column:pwbaofi"`        // 拆出资金
		Tfa          int64 `gorm:"column:tfa"`            // 交易性金融资产
		Cdfa         int64 `gorm:"column:cdfa"`           // 衍生金融资产(流动)
		Nraar        int64 `gorm:"column:nraar"`          // 应收票据及应收账款
		Nr           int64 `gorm:"column:nr"`             // 应收票据
		Ar           int64 `gorm:"column:ar"`             // 应收账款
		Rf           int64 `gorm:"column:rf"`             // 应收款项融资
		Ats          int64 `gorm:"column:ats"`            // 预付款项
		Pr           int64 `gorm:"column:pr"`             // 应收保费
		Rir          int64 `gorm:"column:rir"`            // 应收分保账款
		Crorir       int64 `gorm:"column:crorir"`         // 应收分保合同准备金
		Or           int64 `gorm:"column:or"`             // 其他应收款
		Ir           int64 `gorm:"column:ir"`             // 应收利息
		Dr           int64 `gorm:"column:dr"`             // 应收股利
		Fahursa      int64 `gorm:"column:fahursa"`        // 买入返售金融资产
		I            int64 `gorm:"column:i"`              // 存货
		Ca           int64 `gorm:"column:ca"`             // 合同资产
		Ahfs         int64 `gorm:"column:ahfs"`           // 持有待售资产
		Pe           int64 `gorm:"column:pe"`             // 待摊费用
		Ncadwioy     int64 `gorm:"column:ncadwioy"`       // 一年内到期的非流动资产
		Oca          int64 `gorm:"column:oca"`            // 其他流动资产
		TcaTclR      int64 `gorm:"column:tca_tcl_r"`      // 流动比率
		QR           int64 `gorm:"column:q_r"`            // 速动比率
		Tnca         int64 `gorm:"column:tnca"`           // 非流动资产合计
		TncaTaR      int64 `gorm:"column:tnca_ta_r"`      // 非流动资产占比
		AhTaR        int64 `gorm:"column:ah_ta_r"`        // 重资产占比
		Nclaatc      int64 `gorm:"column:nclaatc"`        // 发放贷款及垫款(非流动)
		Cri          int64 `gorm:"column:cri"`            // 债权投资
		Ocri         int64 `gorm:"column:ocri"`           // 其他债权投资
		Ncafsfa      int64 `gorm:"column:ncafsfa"`        // 可供出售金融资产(非流动)
		Htmi         int64 `gorm:"column:htmi"`           // 持有至到期投资
		Ltar         int64 `gorm:"column:ltar"`           // 长期应收款
		Ltei         int64 `gorm:"column:ltei"`           // 长期股权投资
		Oeii         int64 `gorm:"column:oeii"`           // 其他权益工具投资
		Oncfa        int64 `gorm:"column:oncfa"`          // 其他非流动金融资产
		Rei          int64 `gorm:"column:rei"`            // 投资性房地产
		Fa           int64 `gorm:"column:fa"`             // 固定资产
		Dofa         int64 `gorm:"column:dofa"`           // 固定资产清理
		FaTaR        int64 `gorm:"column:fa_ta_r"`        // 固定资产占总资产比率
		Cip          int64 `gorm:"column:cip"`            // 在建工程
		Es           int64 `gorm:"column:es"`             // 工程物资
		CipFaR       int64 `gorm:"column:cip_fa_r"`       // 在建工程占固定资产比率
		Pba          int64 `gorm:"column:pba"`            // 生产性生物资产
		Oaga         int64 `gorm:"column:oaga"`           // 油气资产
		Pwba         int64 `gorm:"column:pwba"`           // 公益性生物资产
		Roua         int64 `gorm:"column:roua"`           // 使用权资产
		Ia           int64 `gorm:"column:ia"`             // 无形资产
		Rade         int64 `gorm:"column:rade"`           // 开发支出
		Gw           int64 `gorm:"column:gw"`             // 商誉
		GwToeR       int64 `gorm:"column:gw_toe_r"`       // 商誉占净资产比率
		Ltpe         int64 `gorm:"column:ltpe"`           // 长期待摊费用
		Dita         int64 `gorm:"column:dita"`           // 递延所得税资产
		Onca         int64 `gorm:"column:onca"`           // 其他非流动资产
		Tl           int64 `gorm:"column:tl"`             // 负债合计
		Lwi          int64 `gorm:"column:lwi"`            // 有息负债
		LwiTaR       int64 `gorm:"column:lwi_ta_r"`       // 有息负债率
		TlTaR        int64 `gorm:"column:tl_ta_r"`        // 资产负债率
		Tcl          int64 `gorm:"column:tcl"`            // 流动负债合计
		TclTlR       int64 `gorm:"column:tcl_tl_r"`       // 流动负债占比
		Stl          int64 `gorm:"column:stl"`            // 短期借款
		Bfcb         int64 `gorm:"column:bfcb"`           // 向中央银行借款
		Pfbaofi      int64 `gorm:"column:pfbaofi"`        // 拆入资金
		Tfl          int64 `gorm:"column:tfl"`            // 交易性金融负债
		Dfl          int64 `gorm:"column:dfl"`            // 衍生金融负债
		Npaap        int64 `gorm:"column:npaap"`          // 应付票据及应付账款
		Np           int64 `gorm:"column:np"`             // 应付票据
		Ap           int64 `gorm:"column:ap"`             // 应付账款
		Afc          int64 `gorm:"column:afc"`            // 预收账款
		Cl           int64 `gorm:"column:cl"`             // 合同负债
		Fasurpa      int64 `gorm:"column:fasurpa"`        // 卖出回购金融资产
		Dfcab        int64 `gorm:"column:dfcab"`          // 吸收存款及同业存放
		Stoa         int64 `gorm:"column:stoa"`           // 代理买卖证券款
		Ssoa         int64 `gorm:"column:ssoa"`           // 代理承销证券款
		Sawp         int64 `gorm:"column:sawp"`           // 应付职工薪酬
		Tp           int64 `gorm:"column:tp"`             // 应交税费
		Oap          int64 `gorm:"column:oap"`            // 其他应付款
		Intp         int64 `gorm:"column:intp"`           // 应付利息
		Dp           int64 `gorm:"column:dp"`             // 应付股利
		Facp         int64 `gorm:"column:facp"`           // 应付手续费及佣金
		Rip          int64 `gorm:"column:rip"`            // 应付分保账款
		Lhfs         int64 `gorm:"column:lhfs"`           // 持有待售负债
		Ncldwioy     int64 `gorm:"column:ncldwioy"`       // 一年内到期的非流动负债
		Didwioy      int64 `gorm:"column:didwioy"`        // 一年内到期的递延收益
		Cal          int64 `gorm:"column:cal"`            // 预计负债(流动)
		Stbp         int64 `gorm:"column:stbp"`           // 短期应付债券
		Ocl          int64 `gorm:"column:ocl"`            // 其他流动负债
		Tncl         int64 `gorm:"column:tncl"`           // 非流动负债合计
		TnclTlR      int64 `gorm:"column:tncl_tl_r"`      // 非流动负债占比
		Icr          int64 `gorm:"column:icr"`            // 保险合同准备金
		Ltl          int64 `gorm:"column:ltl"`            // 长期借款
		Bp           int64 `gorm:"column:bp"`             // 应付债券
		Psibp        int64 `gorm:"column:psibp"`          // 优先股
		Pcsibp       int64 `gorm:"column:pcsibp"`         // 永续债
		Ll           int64 `gorm:"column:ll"`             // 租赁负债
		Ltap         int64 `gorm:"column:ltap"`           // 长期应付款
		Sap          int64 `gorm:"column:sap"`            // 专项应付款
		Ltpoe        int64 `gorm:"column:ltpoe"`          // 长期应付职工薪酬
		Ncal         int64 `gorm:"column:ncal"`           // 预计负债(非流动)
		Ltdi         int64 `gorm:"column:ltdi"`           // 长期递延收益
		Ditl         int64 `gorm:"column:ditl"`           // 递延所得税负债
		Oncl         int64 `gorm:"column:oncl"`           // 其他非流动负债
		Toe          int64 `gorm:"column:toe"`            // 股东权益合计
		ToeTaR       int64 `gorm:"column:toe_ta_r"`       // 股东权益占比
		Sc           int64 `gorm:"column:sc"`             // 股本
		Oei          int64 `gorm:"column:oei"`            // 其他权益工具
		Psioei       int64 `gorm:"column:psioei"`         // 优先股
		Pcsioei      int64 `gorm:"column:pcsioei"`        // 永续债
		Capr         int64 `gorm:"column:capr"`           // 资本公积
		Is           int64 `gorm:"column:is"`             // 库存股
		Oci          int64 `gorm:"column:oci"`            // 其他综合收益
		Rr           int64 `gorm:"column:rr"`             // 专项储备
		Surr         int64 `gorm:"column:surr"`           // 盈余公积
		Pogr         int64 `gorm:"column:pogr"`           // 一般风险准备金
		Rtp          int64 `gorm:"column:rtp"`            // 未分配利润
		Tetshaoehopc int64 `gorm:"column:tetshaoehopc"`   // 归属于母公司股东及其他权益持有者的权益合计
		Tetoshopc    int64 `gorm:"column:tetoshopc"`      // 归属于母公司普通股股东权益合计
		TetoshopcPs  int64 `gorm:"column:tetoshopc_ps"`   // 归属于母公司普通股股东的每股股东权益
		Etmsh        int64 `gorm:"column:etmsh"`          // 少数股东权益
		Mc           int64 `gorm:"column:mc"`             // 市值
		Tsc          int64 `gorm:"column:tsc"`            // 总股本
		Csc          int64 `gorm:"column:csc"`            // 流通股本
		Shn          int64 `gorm:"column:shn"`            // 股东人数(季度)
		Shbt1shTscR  int64 `gorm:"column:shbt1sh_tsc_r"`  // 第一大股东持仓占总股本比例
		Shbt10shTscR int64 `gorm:"column:shbt10sh_tsc_r"` // 前十大股东持仓占总股本比例
		Shbt10shCscR int64 `gorm:"column:shbt10sh_csc_r"` // 前十大流通股东持仓占流通股本比例
		ShbpoofCscR  int64 `gorm:"column:shbpoof_csc_r"`  // 公募基金持仓占流通股本比例
		PeTtm        int64 `gorm:"column:pe_ttm"`         // PE-TTM
		DPeTtm       int64 `gorm:"column:d_pe_ttm"`       // PE-TTM(扣非)
		Pb           int64 `gorm:"column:pb"`             // PB
		PbWoGw       int64 `gorm:"column:pb_wo_gw"`       // PB(不含商誉)
		PsTtm        int64 `gorm:"column:ps_ttm"`         // PS-TTM
		Dyr          int64 `gorm:"column:dyr"`            // 股息率
	}
)
